name: Check Update Template

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
    secrets:
      npmToken:
        required: true

jobs:
  check-update:
    runs-on: ubuntu-latest
    env:
      HMCL_UPDATE_CHANNEL: ${{ inputs.channel }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Fetch build information
        run: |
          if [ "$HMCL_UPDATE_CHANNEL" == "dev" ]; then
            wget -O lastSuccessfulBuild.json https://ci.huangyuhui.net/job/HMCL/lastSuccessfulBuild/api/json
          else 
            wget -O lastSuccessfulBuild.json https://ci.huangyuhui.net/job/HMCL-stable/lastSuccessfulBuild/api/json
          fi
      - name: Parse version
        run: |
          export HMCL_EXE_FILE_NAME=`cat lastSuccessfulBuild.json | jq -M -r '.artifacts[] | select(.fileName | endswith(".exe")) | .fileName'`
          java ./scripts/ParseVersion.java "$HMCL_UPDATE_CHANNEL" "$HMCL_EXE_FILE_NAME"
      - name: Check for existing version
        run: |
          NEED_UPDATE=true
          HMCL_CURRENT_VERSION=`cat "./channels/$HMCL_UPDATE_CHANNEL/package.json" | jq -M -r '.version'`
          
          if [ "$HMCL_CURRENT_VERSION" == "$HMCL_NPM_VERSION" ]; then 
            NEED_UPDATE=false
          fi
          echo "need_update=$NEED_UPDATE" >> $GITHUB_ENV
      - name: Download artifacts
        if: ${{ env.need_update == 'true' }}
        run: |
          cd "./channels/$HMCL_UPDATE_CHANNEL/"
          
          EXTENSIONS=('exe' 'jar' 'pack' 'pack.gz' 'pack.xz')
          for ext in ${EXTENSIONS[@]}; do
            FILE_NAME="HMCL-$HMCL_VERSION.$ext"
            wget "$HMCL_DOWNLOAD_BASE/$FILE_NAME"
            wget "$HMCL_DOWNLOAD_BASE/$FILE_NAME.sha1"
          
            echo "$(cat "$FILE_NAME.sha1") $FILE_NAME" | sha1sum -c -
          done
          cp "HMCL-$HMCL_VERSION.jar" "HMCL-$HMCL_VERSION.zip" 
          cp "HMCL-$HMCL_VERSION.jar.sha1" "HMCL-$HMCL_VERSION.zip.sha1"
      - name: Update package.json
        if: ${{ env.need_update == 'true' }}
        run: |
          cd "./channels/$HMCL_UPDATE_CHANNEL/"
          cat <<< $(cat package.json | jq -M -r ".version=\"$HMCL_NPM_VERSION\"") > package.json
      - name: Install NPM
        if: ${{ env.need_update == 'true' }}
        run: sudo apt-get install -y npm
      - name: NPM publish
        if: ${{ env.need_update == 'true' }}
        run: |
          cd "./channels/$HMCL_UPDATE_CHANNEL/"
          npm publish --access public .
        env:
          NPM_AUTH_TOKEN: ${{ secrets.npmToken }}
      - name: Generate README
        if: ${{ env.need_update == 'true' }}
        run: ./scripts/generate-readme.sh
      - name: Commit changes
        if: ${{ env.need_update == 'true' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "[BOT] HMCL v$HMCL_VERSION"
      - name: Publish changes
        if: ${{ env.need_update == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
